[database]
# Windows basic install where VERSION is your mariadb version
# path_to_exe = "C:\\Program Files\\MariaDB VERSION\\bin\\mariadbd.exe";
# Linux basic install path
path_to_exe = "/usr/bin/mariadb/"

# These are examples
host = "localhost"
port = 3306
database = "testDB"
username = "root"
password = "root"
allow_local_infile = true
